version: '2'

services:
    unbound:
        restart: always
        build: unbound
        cap_drop:
            - NET_ADMIN
        ports:
            - 192.168.178.74:8853:53/UDP
            - 192.168.178.74:8853:53
        volumes:
            - ./unbound/core/:/etc/unbound/
        networks:
            - dns-net
        entrypoint: /root/init_run.sh

networks:
    dns-net:
        driver: bridge
